---
#jinja2: trim_blocks: "true", lstrip_blocks: "false"
#version: "3.5"
{% for worker in Workers if worker.sshenable %} 
- name: ssh to {{worker.name}}           
  shell: ssh -i ~/.ssh/Shou-En-te.pem ubuntu@{{Masters[0].public_ip_dns}} 'cat ~/.ssh/id_rsa.pub' | ssh -i ~/.ssh/Shou-En-te.pem ubuntu@{{worker.public_ip_dns}} 'cat >> ~/.ssh/authorized_keys'
  
{% endfor %}
